// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoParadigmas.Database;

#nullable disable

namespace Proyecto_Paradigmas.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ProyectoParadigmas.Entities.CatalogItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("CapacidadPersonas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacidad_personas");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroHabitacion")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("numero_habitacion");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT")
                        .HasColumnName("precio");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("catalog_items");
                });

            modelBuilder.Entity("ProyectoParadigmas.Entities.ReservationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CatalogItemId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("catalog_item_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("EstadoTransaccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado_transaccion");

                    b.Property<DateTime>("FechaCheckIn")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_check_in");

                    b.Property<DateTime>("FechaCheckOut")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_check_out");

                    b.Property<DateTime?>("FechaTransaccion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_transaccion");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("TEXT")
                        .HasColumnName("monto_total");

                    b.Property<string>("PayPalOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("paypal_order_id");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("ProyectoParadigmas.Entities.ReservationEntity", b =>
                {
                    b.HasOne("ProyectoParadigmas.Entities.CatalogItemEntity", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");
                });
#pragma warning restore 612, 618
        }
    }
}
